### PR TITLE
Replaced Jaeger.Thrift.VendoredThrift with official ApacheThrift

### PR DESCRIPTION
**Pull request by Falco20019**
## Which problem is this PR solving?
Related to #76 and #116

## Short description of the changes
We like to get rid of `Jaeger.Thrift.VendoredThrift` and use the new official NuGET package. Right now this is not possible, since it's lacking a strong name.

This PR prepares for this this and is kept WIP until strong naming is enabled for the official package.
https://issues.apache.org/jira/browse/THRIFT-4736

### CODE REVIEW

**Comment by rwkarg** [comment]
Just for tracking, the THRIFT issue for signing got duped to https://issues.apache.org/jira/browse/THRIFT-2947

**Comment by Falco20019** [comment]
https://www.nuget.org/packages/ApacheThrift/0.12.0.1 got released with signing. I will check if we can replace the used version `0.11.0` with `0.12.0.1`.

**Comment by Falco20019** [comment]
Thrift 0.12.0.1 does still contain the unsigned DLLs and is therefore not resolving the problem. I created a follow-up issue: https://issues.apache.org/jira/browse/THRIFT-4907

**Comment by Jens-G** [comment]
> Thrift 0.12.0.1 does still contain the unsigned DLLs and is therefore not resolving the problem. I created a follow-up issue: https://issues.apache.org/jira/browse/THRIFT-4907

Incorrect. The DLLs are signed. They just don't have a strong nane. That's not quite the same.

**Comment by Falco20019** [comment]
Regeneration of files for 0.13 is blocked by https://github.com/ahawkins/docker-thrift/pull/22

**Comment by Falco20019** [comment]
Looks like 0.13.0 of ApacheThrift is signed and can be used. Tests are also all green.

**Pull request merged**
