### PR TITLE
Only use 64bit TraceID for compatability

### LINKED ISSUE #81: Correlating traces between csharp and java clients
Im trying to set up a demo to demonstrate tracing across various languages supported by opentracing.

I am running into an issue when trying to get a trace between csharp and java.

I think i have tracked it down to the fact that the traceid generated by the chsarp client is too long.

It seems that the traceid is 32 characters long in the generated header but all the traceids generated by both java and python are only 16 character.

csharp example
e25d900a5c462be7cafa992548dc6d0d

java example
cafa992548dc6d0d

I havent been quite able to get to the bottom of why this might be and what the issue is with the longer id on the java end as it seems to cause an issue and make the java client create a new traceid and breaks the cross process tracing.

I think i have tracked the cause down to the tostring method on TraceID here https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger/TraceId.cs#L38

But im not sure if this is right or wrong.

### PR DESCRIPTION
**Pull request by Falco20019**
Fixes #81 

I added a TODO remark for later fix. I think, the cleanest option would be to have it in `Configuration`. But this would make our `Configuration` and `Tracer` implementations differ from `Java`.

### CODE REVIEW

**Comment by yurishkuro** [comment]
cf. https://github.com/jaegertracing/jaeger/issues/858

**Comment by Falco20019** [comment]
@ScottGuymer yep, just creation now was the problem. When receiving both work and we have unit tests for that.

@yurishkuro Good to have it tracked on meta level. I will merge it once a review form a collaborator was done. I will create another issue to track the second part with configurability.

**Comment by ScottGuymer** [comment]
How does this get pushed out to nuget now it's been merged?

**Comment by Falco20019** [comment]
There is a second issue that should be included in this version (#80). Deadline I gave is Sunday. Do you need it today or is tomorrow early enough? If you need it earlier, I could do a pre-release.

**Comment by ScottGuymer** [comment]
No rush. Probably won't be working on it again until monday anyway.

**Pull request merged**
