### PR TITLE
Updated NuGET packages

### PR DESCRIPTION
**Pull request by Falco20019**
## Which problem is this PR solving?
- Microsoft.AspNetCore.All < 2.0.9 has some security issues

## Short description of the changes
- Updated all non-thrift packages to current versions.

@cwe1ss Is it problematic to update `Microsoft.Extensions.Logging.Abstractions` or any other package in our libraries?

### CODE REVIEW

**Comment by cwe1ss** [comment]
.NET Core 2.0 has recently [reached end of life](https://github.com/dotnet/announcements/issues/86) so I guess it should be fine to update the logging library to `2.1.x`.

**Comment by cwe1ss** [comment]
So you could also update all examples to .NET Core 2.1 if you want?!

**Comment by Falco20019** [comment]
Good idea. Didn’t think about the EOL for 2.0 :)

**Comment by Falco20019** [comment]
@cwe1ss Have updated and upgraded everything to netcoreapp2.1 and solved some warnings.

**Comment by Falco20019** [comment]
I removed the examples from build to avoid a problem with `Microsoft.WebApplication.targets` in `Jaeger.Example.WebApi.NetFx`. `Jaeger.Example.WebApi` would work but I think we should also keep it out since we don't really generate artefacts from it.

**Comment by Falco20019** [comment]
@cwe1ss Friendly ping :)

**Comment by Falco20019** [comment]
@cwe1ss @grounded042 Would be great if one of you could have a quick look and approve the review.

**Pull request merged**
